/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/value_exile" |
       "/pages/about/about" |
       "/pages/index/add_message" |
       "/pages/index/exchange_record" |
       "/pages/index/index" |
       "/pages/index/instead_details" |
       "/pages/index/instead_repair" |
       "/pages/index/learning_growth" |
       "/pages/index/leave_message" |
       "/pages/index/low_carbon" |
       "/pages/index/mall" |
       "/pages/index/points_record" |
       "/pages/index/product_detials" |
       "/pages/index/rank" |
       "/pages/index/study_result";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/about/about"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
